// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Package skus provides a lookup table of Azure VM SKU names to their vCPU counts,
// sourced from the embedded known_skus.yaml file generated by hack/code/sku_gen.
package skus

import (
	_ "embed"
	"sync"

	"gopkg.in/yaml.v3"
)

//go:embed known_skus.yaml
var rawYAML []byte

type skuEntry struct {
	Name  string `yaml:"name"`
	VCPUs int    `yaml:"vcpus"`
}

var (
	once      sync.Once
	lookupMap map[string]int
)

func init() {
	once.Do(load)
}

func load() {
	var entries []skuEntry
	if err := yaml.Unmarshal(rawYAML, &entries); err != nil {
		lookupMap = map[string]int{}
		return
	}
	m := make(map[string]int, len(entries))
	for _, e := range entries {
		m[e.Name] = e.VCPUs
	}
	lookupMap = m
}

// Lookup returns the vCPU count for the given Azure VM SKU name.
// Returns 0 if the SKU is not found in the embedded table.
func Lookup(skuName string) int {
	return lookupMap[skuName]
}
