// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Package skus provides a lookup table of Azure VM SKU names to their vCPU counts,
// sourced from the embedded known_skus.yaml file generated by hack/code/sku_gen.
package skus

import (
	_ "embed"
	"sync"

	"gopkg.in/yaml.v3"
)

//go:embed known_skus.yaml
var rawYAML []byte

// SKU represents a single Azure VM SKU entry with its hardware characteristics.
type SKU struct {
	Name                  string  `yaml:"name"                  json:"name"`
	Family                string  `yaml:"family"                json:"family"`
	VCPUs                 int     `yaml:"vcpus"                 json:"vcpus"`
	MemoryGB              float64 `yaml:"memoryGb"              json:"memoryGb"`
	GPUCount              int     `yaml:"gpuCount"              json:"gpuCount"`
	MaxDataDisks          int     `yaml:"maxDataDisks"          json:"maxDataDisks"`
	AcceleratedNetworking bool    `yaml:"acceleratedNetworking" json:"acceleratedNetworking"`
}

var (
	once    sync.Once
	skuMap  map[string]SKU
	allSKUs []SKU
)

func init() {
	once.Do(load)
}

func load() {
	var entries []SKU
	if err := yaml.Unmarshal(rawYAML, &entries); err != nil {
		skuMap = map[string]SKU{}
		allSKUs = []SKU{}
		return
	}
	skuMap = make(map[string]SKU, len(entries))
	allSKUs = make([]SKU, 0, len(entries))
	for _, e := range entries {
		skuMap[e.Name] = e
		allSKUs = append(allSKUs, e)
	}
}

// Lookup returns the full SKU entry for the given Azure VM SKU name.
// The second return value is false if the SKU is not found.
func Lookup(skuName string) (SKU, bool) {
	s, ok := skuMap[skuName]
	return s, ok
}

// ListAll returns all known SKU entries.
func ListAll() []SKU {
	return allSKUs
}
