// Check if CosmosDB disables write operations on metadata resources via account keys
resources
| where type =~ 'Microsoft.DocumentDB/databaseAccounts'
| extend metadataWriteDisabled = properties.disableKeyBasedMetadataWriteAccess
| where isnull(metadataWriteDisabled) or metadataWriteDisabled == false
| extend recommendationId = 'cosmos-009'
| extend param1 = ''
| project recommendationId, name, id, tags, param1
