// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package aigov

// Azure bills Claude-on-Foundry usage through Consumption Units (CCU) at a
// fixed rate of 100 CCU = $1 (that is, $0.01 per CCU). The dollar rates below
// are converted from that fixed rate by Anthropic/Azure, so estimating cost
// directly from these USD-per-MTok numbers yields the same dollar amount as
// the underlying CCU billing without needing to model the CCU count itself.

// claudeModelPrice is one entry in the Claude pricing snapshot, generated by
// hack/code/claude_pricing_gen from the official Anthropic pricing page into
// zz_generated.claude_pricing.go (claudePricingData). See that file for
// provenance (source URL, fetch date).
type claudeModelPrice struct {
	Model            string
	Aliases          []string
	InputPerMTokUSD  float64
	OutputPerMTokUSD float64
}

var claudePriceByModel map[string]claudeModelPrice

func init() {
	loadClaudePricing()
}

func loadClaudePricing() {
	claudePriceByModel = make(map[string]claudeModelPrice, len(claudePricingData))
	for _, e := range claudePricingData {
		claudePriceByModel[canonicalModelName(e.Model)] = e
		for _, alias := range e.Aliases {
			claudePriceByModel[canonicalModelName(alias)] = e
		}
	}
}

// resolveClaudePrice looks up the CCU-equivalent USD rate for a Claude model
// from the embedded static snapshot. It never guesses from a similar model:
// an unlisted model returns ok=false.
func resolveClaudePrice(modelName string) (priceResolution, bool) {
	entry, ok := claudePriceByModel[canonicalModelName(modelName)]
	if !ok {
		return priceResolution{}, false
	}
	return priceResolution{
		InputPerMTokUSD:  entry.InputPerMTokUSD,
		OutputPerMTokUSD: entry.OutputPerMTokUSD,
		Source:           "claude_ccu_equivalent",
	}, true
}
