// Code generated by hack/code/claude_pricing_gen; DO NOT EDIT.
// Regenerate with: make claude-pricing
// Pricing source: https://platform.claude.com/docs/en/about-claude/pricing
// Fetched on: 2025-01-01 (seed snapshot pending first generator run)
//
// Azure bills Claude-on-Foundry usage through Consumption Units (CCU) at a
// fixed rate of 100 CCU = $1. The dollar rates below are the CCU-equivalent
// cost per million tokens, labelled "claude_ccu_equivalent" (rather than
// "exact retail rate") at resolution time.

package aigov

// claudePricingData is the embedded Claude/Anthropic pricing snapshot used by
// resolveClaudePrice. See claude_pricing.go for the lookup logic.
var claudePricingData = []claudeModelPrice{
	{
		Model:            "claude-opus-4.5",
		Aliases:          []string{"claude-opus-4-5"},
		InputPerMTokUSD:  5.0,
		OutputPerMTokUSD: 25.0,
	},
	{
		Model:            "claude-sonnet-4.5",
		Aliases:          []string{"claude-sonnet-4-5", "claude-sonnet-4"},
		InputPerMTokUSD:  3.0,
		OutputPerMTokUSD: 15.0,
	},
	{
		Model:            "claude-haiku-4.5",
		Aliases:          []string{"claude-haiku-4-5"},
		InputPerMTokUSD:  1.0,
		OutputPerMTokUSD: 5.0,
	},
}
