// Azure Resource Graph Query
// Get all Front Door WAF policies that are not associated without associations
resources
| where type == "microsoft.network/frontdoorwebapplicationfirewallpolicies"
| where properties.frontendEndpointLinks== "[]" and properties.securityPolicyLinks == "[]"
| project recommendationId="0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a", name, id, tags, param1=strcat("Sku: ", sku.name)
