// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package scanners

import (
	"github.com/Azure/azqr/internal/azqr"
	"github.com/Azure/azqr/internal/scanners/aa"
	"github.com/Azure/azqr/internal/scanners/adf"
	"github.com/Azure/azqr/internal/scanners/afd"
	"github.com/Azure/azqr/internal/scanners/afw"
	"github.com/Azure/azqr/internal/scanners/agw"
	"github.com/Azure/azqr/internal/scanners/aks"
	"github.com/Azure/azqr/internal/scanners/amg"
	"github.com/Azure/azqr/internal/scanners/apim"
	"github.com/Azure/azqr/internal/scanners/appcs"
	"github.com/Azure/azqr/internal/scanners/appi"
	"github.com/Azure/azqr/internal/scanners/as"
	"github.com/Azure/azqr/internal/scanners/asp"
	"github.com/Azure/azqr/internal/scanners/avd"
	"github.com/Azure/azqr/internal/scanners/avs"
	"github.com/Azure/azqr/internal/scanners/ba"
	"github.com/Azure/azqr/internal/scanners/ca"
	"github.com/Azure/azqr/internal/scanners/cae"
	"github.com/Azure/azqr/internal/scanners/ci"
	"github.com/Azure/azqr/internal/scanners/cog"
	"github.com/Azure/azqr/internal/scanners/conn"
	"github.com/Azure/azqr/internal/scanners/cosmos"
	"github.com/Azure/azqr/internal/scanners/cr"
	"github.com/Azure/azqr/internal/scanners/dbw"
	"github.com/Azure/azqr/internal/scanners/dec"
	"github.com/Azure/azqr/internal/scanners/disk"
	"github.com/Azure/azqr/internal/scanners/erc"
	"github.com/Azure/azqr/internal/scanners/evgd"
	"github.com/Azure/azqr/internal/scanners/evh"
	"github.com/Azure/azqr/internal/scanners/fdfp"
	"github.com/Azure/azqr/internal/scanners/gal"
	"github.com/Azure/azqr/internal/scanners/hpc"
	"github.com/Azure/azqr/internal/scanners/iot"
	"github.com/Azure/azqr/internal/scanners/it"
	"github.com/Azure/azqr/internal/scanners/kv"
	"github.com/Azure/azqr/internal/scanners/lb"
	"github.com/Azure/azqr/internal/scanners/log"
	"github.com/Azure/azqr/internal/scanners/logic"
	"github.com/Azure/azqr/internal/scanners/maria"
	"github.com/Azure/azqr/internal/scanners/mysql"
	"github.com/Azure/azqr/internal/scanners/netapp"
	"github.com/Azure/azqr/internal/scanners/ng"
	"github.com/Azure/azqr/internal/scanners/nsg"
	"github.com/Azure/azqr/internal/scanners/nw"
	"github.com/Azure/azqr/internal/scanners/pdnsz"
	"github.com/Azure/azqr/internal/scanners/pep"
	"github.com/Azure/azqr/internal/scanners/pip"
	"github.com/Azure/azqr/internal/scanners/psql"
	"github.com/Azure/azqr/internal/scanners/redis"
	"github.com/Azure/azqr/internal/scanners/rsv"
	"github.com/Azure/azqr/internal/scanners/rt"
	"github.com/Azure/azqr/internal/scanners/sap"
	"github.com/Azure/azqr/internal/scanners/sb"
	"github.com/Azure/azqr/internal/scanners/sigr"
	"github.com/Azure/azqr/internal/scanners/sql"
	"github.com/Azure/azqr/internal/scanners/st"
	"github.com/Azure/azqr/internal/scanners/synw"
	"github.com/Azure/azqr/internal/scanners/traf"
	"github.com/Azure/azqr/internal/scanners/vdpool"
	"github.com/Azure/azqr/internal/scanners/vgw"
	"github.com/Azure/azqr/internal/scanners/vm"
	"github.com/Azure/azqr/internal/scanners/vmss"
	"github.com/Azure/azqr/internal/scanners/vnet"
	"github.com/Azure/azqr/internal/scanners/wps"
)

// GetScanners returns a list of all scanners
func GetScanners() []azqr.IAzureScanner {
	return []azqr.IAzureScanner{
		&aa.AutomationAccountScanner{},
		&dbw.DatabricksScanner{},
		&adf.DataFactoryScanner{},
		&afd.FrontDoorScanner{},
		&afw.FirewallScanner{},
		&agw.ApplicationGatewayScanner{},
		&aks.AKSScanner{},
		&amg.ManagedGrafanaScanner{},
		&apim.APIManagementScanner{},
		&appcs.AppConfigurationScanner{},
		&appi.AppInsightsScanner{},
		&as.AnalysisServicesScanner{},
		&avs.AVSScanner{},
		&avd.AzureVirtualDesktopScanner{},
		&ba.BatchAccountScanner{},
		&cae.ContainerAppsEnvironmentScanner{},
		&ca.ContainerAppsScanner{},
		&ci.ContainerInstanceScanner{},
		&cog.CognitiveScanner{},
		&conn.ConnectionScanner{},
		&cosmos.CosmosDBScanner{},
		&cr.ContainerRegistryScanner{},
		&dec.DataExplorerScanner{},
		&disk.DiskScanner{},
		&erc.ExpressRouteScanner{},
		&evgd.EventGridScanner{},
		&evh.EventHubScanner{},
		&fdfp.FrontDoorWAFPolicyScanner{},
		&hpc.HighPerformanceComputingScanner{},
		&it.ImageTemplateScanner{},
		&iot.IoTHubScanner{},
		&gal.GalleryScanner{},
		&kv.KeyVaultScanner{},
		&lb.LoadBalancerScanner{},
		&log.LogAnalyticsScanner{},
		&logic.LogicAppScanner{},
		&maria.MariaScanner{},
		&mysql.MySQLFlexibleScanner{},
		&mysql.MySQLScanner{},
		&ng.NatGatewayScanner{},
		&netapp.NetAppScanner{},
		&nsg.NSGScanner{},
		&nw.NetworkWatcherScanner{},
		&asp.AppServiceScanner{},
		&pep.PrivateEndpointScanner{},
		&pip.PublicIPScanner{},
		&pdnsz.PrivateDNSZoneScanner{},
		&psql.PostgreFlexibleScanner{},
		&psql.PostgreScanner{},
		&rt.RouteTableScanner{},
		&rsv.RecoveryServiceScanner{},
		&redis.RedisScanner{},
		&sap.SAPScanner{},
		&sb.ServiceBusScanner{},
		&sigr.SignalRScanner{},
		&sql.SQLScanner{},
		&synw.SynapseWorkspaceScanner{},
		&traf.TrafficManagerScanner{},
		&st.StorageScanner{},
		&vdpool.VirtualDesktopScanner{},
		&vm.VirtualMachineScanner{},
		&vmss.VirtualMachineScaleSetScanner{},
		&vnet.VirtualNetworkScanner{},
		&vgw.VirtualNetworkGatewayScanner{},
		&wps.WebPubSubScanner{},
	}
}
